# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20170823_0925'),
        ('timetables', '0002_auto_20170823_0907'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set([('doctor', 'day_of_week')]),
        ),
    ]
