# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20170823_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
