# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_auto_20170823_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='sorder',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='sorder',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterIndexTogether(
            name='doctor',
            index_together=set([('first_name', 'last_name')]),
        ),
    ]
